// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// AdminLoginData represents data for the admin login page
type AdminLoginData struct {
	Error string
}

// AdminLoginPage renders the admin login page
func AdminLoginPage(data AdminLoginData) templ.Component {
	return BaseLayout(
		"Admin Login - Mewling Goat Tavern",
		"Secure admin access for movie poll management",
		AdminLoginContent(data),
	)
}

// AdminLoginContent renders the admin login form
func AdminLoginContent(data AdminLoginData) templ.Component {
	return AdminLoginTemplate(data)
}

func AdminLoginTemplate(data AdminLoginData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"min-h-screen flex items-center justify-center bg-gradient-to-br from-goat-900 via-goat-800 to-goat-900\"><div class=\"max-w-md w-full space-y-8 p-8\"><div class=\"text-center\"><h1 class=\"text-4xl font-bold text-tavern-500 mb-2\">🔐 Admin Access</h1><p class=\"text-goat-300\">Enter your credentials to access the admin panel</p></div><div id=\"login-result\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if data.Error != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"bg-red-900/20 border border-red-500/50 text-red-300 px-4 py-3 rounded-lg mb-4\"><p class=\"font-semibold\">Error:</p><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(data.Error)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/admin-login.templ`, Line: 33, Col: 21}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><form hx-post=\"/api/admin/login\" hx-target=\"body\" hx-swap=\"outerHTML\" class=\"space-y-6\"><div><label for=\"username\" class=\"block text-sm font-medium text-goat-300 mb-2\">Username</label> <input type=\"text\" id=\"username\" name=\"username\" required class=\"w-full px-4 py-3 bg-goat-700 text-goat-100 rounded-lg border border-goat-600 focus:border-tavern-400 focus:outline-none focus:ring-2 focus:ring-tavern-400/20\" placeholder=\"Enter your username\"></div><div><label for=\"password\" class=\"block text-sm font-medium text-goat-300 mb-2\">Password</label> <input type=\"password\" id=\"password\" name=\"password\" required class=\"w-full px-4 py-3 bg-goat-700 text-goat-100 rounded-lg border border-goat-600 focus:border-tavern-400 focus:outline-none focus:ring-2 focus:ring-tavern-400/20\" placeholder=\"Enter your password\"></div><button type=\"submit\" class=\"w-full bg-tavern-500 hover:bg-tavern-600 text-white py-3 px-4 rounded-lg transition-colors font-semibold\">Sign In</button></form><div class=\"text-center\"><a href=\"/\" class=\"text-goat-400 hover:text-tavern-400 text-sm\">← Back to Movie Poll</a></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
