root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/server"
cmd = "go build -o ./tmp/server ."
delay = 1000
env = []
exclude_dir = ["assets", "tmp", "vendor", "testdata", "static"]
exclude_file = []
exclude_regex = ["_test.go", ".*_templ\\.go$"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "templ"]
include_file = []
kill_delay = "5s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = ["sleep 1", "lsof -ti:3000 | xargs -r kill -9 2>/dev/null || true"]
pre_cmd = ["go run github.com/a-h/templ/cmd/templ@latest generate", "lsof -ti:3000 | xargs -r kill -9 2>/dev/null || true"]
rerun = false
rerun_delay = 1500
send_interrupt = true
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true
